name: PocketTelegram
version: 1.2
description: The Telegram Bot API for PocketMine-MP with many features.
author: ChalkPE
main: ChalkPE\PocketTelegram\PocketTelegram
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6]
