name: PocketTelegram
version: "1.2"
description: The Telegram Bot API for PocketMine-MP with many features

author: ChalkPE
website: http://chalk.pe

main: ChalkPE\PocketTelegram\PocketTelegram
api: 3.0.0-ALPHA7
